<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\Common\IOBootstrap.NET.Common.csproj" />
    <ProjectReference Include="..\..\Batch\Base\IOBootstrap.NET.Batch.Base.csproj" />
    <ProjectReference Include="..\..\Batch\PushSender\IOBootstrap.NET.Batch.PushSender.csproj" />
    <ProjectReference Include="..\..\DataAccess\IOBootstrap.NET.DataAccess.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <!-- <PackageReference Include="MySql.EntityFrameworkCore" Version="9.0.0" /> -->
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugType>full</DebugType>
    <DefineConstants>USE_POSTGRES_DATABASE;DEBUG;</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Staging' ">
    <DebugType>full</DebugType>
    <DefineConstants>USE_POSTGRES_DATABASE;DEBUG</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <NoStdLib>false</NoStdLib>
    <DefineConstants>USE_POSTGRES_DATABASE;RELEASE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="batchsettings*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory> 
    </Content>
  </ItemGroup>
</Project>
