desc "Build modules"
lane :build_modules do |options|
    environment = options[:environment]
    react(
        sources_directory: Dir.pwd + "/../../../../React.UI",
        environment: environment,
        print_output: false
    )
end

desc "Build backoffice"
lane :build_backoffice do |options|
    environment = options[:environment]
    react(
        sources_directory: Dir.pwd + "/../../../../Backoffice.UI",
        environment: environment,
        output_directory: Dir.pwd + "/../../../../API-Files/Staging/wwwroot/backoffice"
    )
end

desc "Build react"
lane :build_react_staging do
    build_modules(environment: "staging")
    build_backoffice(environment: "staging")
end