# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# update_fastlane

desc "Build backend"
lane :build_backend do |options|
    environment = options[:environment]
    dotnet(
        solution_directory: Dir.pwd + "/../",
        environment: environment,
        output_directory: Dir.pwd + "/../API-Files/Staging"
    )
end

desc "Build backend staging"
lane :build_backend_staging do
    build_backend(environment: "Staging")
end

desc "Build modules"
lane :build_modules do |options|
    environment = options[:environment]
    react(
        sources_directory: Dir.pwd + "/../React.UI",
        environment: environment,
        print_output: false
    )
end

desc "Build backoffice"
lane :build_backoffice do |options|
    environment = options[:environment]
    react(
        sources_directory: Dir.pwd + "/../Backoffice.UI",
        environment: environment,
        output_directory: Dir.pwd + "/../API-Files/Staging/wwwroot/backoffice"
    )
end

desc "Build react"
lane :build_react_staging do
    build_modules(environment: "staging")
    build_backoffice(environment: "staging")
end

desc "Build all staging"
lane :build_all_staging do
    build_backend_staging
    build_react_staging
end